# docker-compose.yml
services:
  # Layanan Aplikasi (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laundry_balap_kuda_app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html # Sinkronisasi kode aplikasi Anda
    networks:
      - laundry_balap_kuda_network
    depends_on:
      - db

  # Layanan Web Server (Nginx)
  webserver:
    image: nginx:alpine
    container_name: laundry_balap_kuda_webserver
    restart: unless-stopped
    ports:
      - "8080:80" # Akses aplikasi dari host melalui port 8080
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laundry_balap_kuda_network
    depends_on:
      - app

  # Layanan Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: laundry_balap_kuda_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Untuk koneksi ke DB dari luar Docker (opsional)
    networks:
      - laundry_balap_kuda_network

# Definisi Networks & Volumes
networks:
  laundry_balap_kuda_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
